apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - web.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  managed-by: code2k8s
